import 'dotenv/config';
import { WebSocket } from 'ws';
import { 
  httpClientProofProvider 
} from '@midnight-ntwrk/midnight-js-http-client-proof-provider';
import { 
  indexerPublicDataProvider 
} from '@midnight-ntwrk/midnight-js-indexer-public-data-provider';
import { 
  HDWallet,
  Roles 
} from '@midnight-ntwrk/wallet-sdk-hd';
import { mnemonicToSeedSync } from '@scure/bip39';
import { 
  deployContract,
  findDeployedContract,
  type DeployedContract,
  type ContractProviders
} from '@midnight-ntwrk/midnight-js-contracts';

// Note: Contract types are generated by 'compact' into ./gen/
import * as BlindSwarmContract from './gen/contract/index.js';

export interface ClientConfig {
  providerUrl: string; // The RPC node
  indexerUrl: string;  // The Indexer node
  seed: string;        // 64-char hex seed (from mnemonic)
  mnemonicPhrase?: string; // Optional: 24-word recovery phrase (alternative to seed)
  contractAddress?: string;
}

export interface DeployResult {
  contractAddress: string;
  transactionId: string;
}

/**
 * BlindSwarm Real Production Client (SDK Pure)
 */
class MidnightClient {
  private config: ClientConfig;
  private providers: ContractProviders<any, any, any>;
  private wallet: any = null;
  private contract: DeployedContract<any> | null = null;

  constructor(config: ClientConfig) {
    this.config = config;
    
    // 1. Initialize Proof Provider (localhost:6300)
    const proofProvider = httpClientProofProvider(
      'http://localhost:6300',
      { getZKConfig: async () => ({}) } as any
    );
    
    // 2. Initialize Indexer Provider
    // Note: graphql-ws 6.x requires explicit WebSocket implementation
    // Cast to any to bypass type mismatch between @types/ws and graphql-ws expectations
    const publicDataProvider = indexerPublicDataProvider(
      config.indexerUrl, 
      config.indexerUrl.replace('http', 'ws'),
      WebSocket as any
    );
    
    // Satisfy the full MidnightProviders interface
    this.providers = {
      zkConfigProvider: { getZKConfig: async () => ({}) } as any,
      proofProvider,
      publicDataProvider,
      walletProvider: null as any,
      privateStateProvider: {
        get: async () => undefined,
        set: async () => {},
      } as any,
      witnessProvider: {
        secretKey: async () => {
          if (!this.config.seed) throw new Error('Seed missing for witness');
          return Buffer.from(this.config.seed.slice(0, 64), 'hex');
        }
      } as any,
      midnightProvider: {
        getLedgerParameters: async () => ({}) as any,
        submitTx: async () => ({}) as any,
      } as any,
    } as any;
  }

  /**
   * Initialize the real HD Wallet.
   * Supports both a pre-derived 64-char hex seed OR a 24-word mnemonic phrase.
   */
  async initWallet(): Promise<void> {
    let seedHex = this.config.seed;
    
    // If no seed provided, try to derive from mnemonic
    if (!seedHex && this.config.mnemonicPhrase) {
      console.log('[REAL-ORCH] Deriving seed from mnemonic phrase...');
      const mnemonic = this.config.mnemonicPhrase.trim();
      
      // Validate mnemonic length (24 words)
      const words = mnemonic.split(/\s+/);
      if (words.length !== 24) {
        throw new Error('Mnemonic must be exactly 24 words');
      }
      
      // Convert mnemonic to seed using BIP39
      const seedBytes = mnemonicToSeedSync(mnemonic);
      seedHex = Buffer.from(seedBytes).toString('hex');
      
      console.log('[REAL-ORCH] Seed derived from mnemonic (first 32 chars):', seedHex.slice(0, 32) + '...');
    }
    
    if (!seedHex || seedHex.length !== 64) {
      throw new Error('CRITICAL: Either MIDNIGHT_WALLET_SEED (64-char hex) or MIDNIGHT_MNEMONIC (24 words) is required in .env.');
    }
    
    const seedBuffer = Buffer.from(seedHex, 'hex');
    const result = HDWallet.fromSeed(seedBuffer);
    
    if (result.type !== 'seedOk') {
      throw new Error(`CRITICAL: Wallet initialization failed: ${result.type}`);
    }
    
    this.wallet = result.hdWallet;
    // @ts-ignore
    this.providers.walletProvider = this.wallet;
    console.log(`[REAL-ORCH] Wallet connected via Midnight HDWallet SDK.`);
  }

  get walletAddress(): string {
    if (!this.wallet) throw new Error('Wallet not initialized');
    return this.wallet.address;
  }

  /**
   * ACTUAL deployment of the provided contract logic.
   */
  async deployContract(compiledContract: any): Promise<DeployResult> {
    if (!this.wallet) await this.initWallet();
    
    console.log('[REAL-ORCH] Deploying contract to preprod network...');
    
    // Using a more flexible call for compiledContract since types aren't generated yet
    const deployed = await deployContract(this.providers, {
      compiledContract,
      // @ts-ignore
      args: [] 
    } as any);
    
    this.contract = deployed as any;
    
    return { 
      // @ts-ignore
      contractAddress: deployed.deployTxData.public.contractAddress, 
      // @ts-ignore
      transactionId: (deployed.deployTxData.public as any).txId || 'confirmed' 
    };
  }

  /**
   * ACTUAL joining of an existing contract.
   */
  async joinContract(compiledContract: any, contractAddress: string): Promise<void> {
    if (!this.wallet) await this.initWallet();
    
    this.contract = (await findDeployedContract(this.providers, {
      compiledContract,
      contractAddress
    } as any)) as any;
  }

  async registerAgent(capabilities: string[], stake: bigint): Promise<{ agentId: string }> {
    if (!this.contract) throw new Error('No active contract session');
    
    // Match contract expect Bytes<64>
    const capabilitiesBytes = new Uint8Array(64);
    // @ts-ignore
    await this.contract.callTx.register_agent(capabilitiesBytes, stake);
    
    return { agentId: this.walletAddress };
  }

  async createTask(taskId: string, escrow: bigint, deadline: number): Promise<{ taskId: string }> {
    if (!this.contract) throw new Error('No active contract session');
    
    // @ts-ignore
    await this.contract.callTx.create_task(Buffer.from(taskId, 'hex'), escrow, BigInt(deadline));
    
    return { taskId };
  }

  async assignStep(taskId: string, stepIndex: number, agentId: string): Promise<void> {
    if (!this.contract) throw new Error('No active contract session');
    
    // @ts-ignore
    await this.contract.callTx.assign_step(taskId, stepIndex, agentId);
  }

  async submitAttestation(
    taskId: string,
    stepBytes: Uint8Array,
    outputHash: string
  ): Promise<{ success: boolean }> {
    if (!this.contract) throw new Error('No active contract session');
    
    // Updated to match 3-argument signature: (task_id, step_bytes, output_hash)
    // @ts-ignore
    await this.contract.callTx.submit_attestation(
      Buffer.from(taskId, 'hex'), 
      stepBytes, 
      Buffer.from(outputHash.padEnd(64, '0').slice(0, 64), 'hex')
    );
    
    return { success: true };
  }

  async getContractState(): Promise<any> {
    if (!this.contract) throw new Error('No active contract session');
    return {}; 
  }

  watchEvent(eventName: string, handler: (data: any) => void): void {
    if (!this.contract) return;
    console.log(`[REAL-ORCH] Watching for on-chain event: ${eventName}`);
  }
}

export async function createClient(config: any): Promise<MidnightClient> {
    return new MidnightClient({
        providerUrl: process.env.MIDNIGHT_PROVIDER_URL || 'https://rpc.preprod.midnight.network',
        indexerUrl: process.env.MIDNIGHT_INDEXER_URL || 'https://indexer.preprod.midnight.network/api/v3/graphql',
        seed: config.walletPrivateKey || process.env.MIDNIGHT_WALLET_SEED || '',
        mnemonicPhrase: config.mnemonicPhrase || process.env.MIDNIGHT_MNEMONIC || undefined,
        contractAddress: config.contractAddress
    });
}

export { MidnightClient };





